//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDTk22cnt3_lession111DB_2210900065.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLDTk22cnt3Lession11DbEntities : DbContext
    {
        public NLDTk22cnt3Lession11DbEntities()
            : base("name=NLDTk22cnt3Lession11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NLDTCategory> NLDTCategory { get; set; }
        public virtual DbSet<NLDTProduct> NLDTProduct { get; set; }
    }
}
