//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDTk22cnt3_lession111DB_2210900065.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NLDTProduct
    {
        public string NLDTid { get; set; }
        public string NLDTProName { get; set; }
        public Nullable<int> NLDTQty { get; set; }
        public Nullable<double> NLDTPrice { get; set; }
        public Nullable<int> NLDTCateid { get; set; }
        public Nullable<bool> NLDTActive { get; set; }
    }
}
