//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLDTk22cnt3_lession111DB_2210900065.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NLDTCategory
    {
        [Display(Name ="ma danh muc")]
        public int NLDTid { get; set; }
        [Display(Name = "ten danh muc")]
        public string NLDTCreateName { get; set; }
        [Display(Name = "trang thai")]
        public Nullable<bool> NLDTStatus { get; set; }
    }
}
